brute_force:
  enabled: yes
  randomize: yes
  sim_time:
    enabled: yes
    window: 72
  enabled: yes
  time_window: 5m
  num_attempts_thresh: 2
  num_failures_thresh: 1
  threat_level: medium

multi_logins:
  enabled: yes
  randomize: yes
  sim_time:
    enabled: yes
    window: 72
  time_window: 5m
  unique_logins_thresh: 1
  threat_level: low

website_blacklist:
  enabled: yes
  randomize: yes
  sim_time:
    enabled: yes
    window: 72
  max_searches: 10
  websites:
      151.101.1.140: reddit.com
      157.240.8.35: facebook.com
      172.217.167.78: google.com
      172.217.25.174: youtube.com
  threat_level: high

geo_locations:
  enabled: yes
  default_locations:
      enabled: yes
      locations: [UWA]
  locations:
    UWA:
      enabled: yes
      boundary:
        top_left: [-31.976653, 115.816020]
        bottom_right: [-31.985883, 115.819904]
      num_nodes: 30
      static_node_coordinates:
        enabled: no
      bias_threat_coordinates:
        enabled: yes
        concentration: 0.4
